POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Spice and More Spice Makes Everything Nice",
  "author": "Ashley Benhayoun",
  "url": "https://www.hyperflyer.com/explore-sf/spice-and-more-spice-makes-everything-nice/",
  "likes": 0
}
